name: Build Leyo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Télécharger dépendances Go
        run: go mod tidy

      - name: Build Wails
        run: wails build -o Leyo.exe -icon build/windows/logo.ico

      - name: Uploader le binaire
        uses: actions/upload-artifact@v4
        with:
          name: leyo-windows
          path: build/bin/Leyo.exe